require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DemoUsersController do

  # This should return the minimal set of attributes required to create a valid
  # DemoUser. As you add validations to DemoUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DemoUsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all demo_users as @demo_users" do
      demo_user = DemoUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:demo_users).should eq([demo_user])
    end
  end

  describe "GET show" do
    it "assigns the requested demo_user as @demo_user" do
      demo_user = DemoUser.create! valid_attributes
      get :show, {:id => demo_user.to_param}, valid_session
      assigns(:demo_user).should eq(demo_user)
    end
  end

  describe "GET new" do
    it "assigns a new demo_user as @demo_user" do
      get :new, {}, valid_session
      assigns(:demo_user).should be_a_new(DemoUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested demo_user as @demo_user" do
      demo_user = DemoUser.create! valid_attributes
      get :edit, {:id => demo_user.to_param}, valid_session
      assigns(:demo_user).should eq(demo_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DemoUser" do
        expect {
          post :create, {:demo_user => valid_attributes}, valid_session
        }.to change(DemoUser, :count).by(1)
      end

      it "assigns a newly created demo_user as @demo_user" do
        post :create, {:demo_user => valid_attributes}, valid_session
        assigns(:demo_user).should be_a(DemoUser)
        assigns(:demo_user).should be_persisted
      end

      it "redirects to the created demo_user" do
        post :create, {:demo_user => valid_attributes}, valid_session
        response.should redirect_to(DemoUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved demo_user as @demo_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        DemoUser.any_instance.stub(:save).and_return(false)
        post :create, {:demo_user => {  }}, valid_session
        assigns(:demo_user).should be_a_new(DemoUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DemoUser.any_instance.stub(:save).and_return(false)
        post :create, {:demo_user => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested demo_user" do
        demo_user = DemoUser.create! valid_attributes
        # Assuming there are no other demo_users in the database, this
        # specifies that the DemoUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DemoUser.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => demo_user.to_param, :demo_user => { "these" => "params" }}, valid_session
      end

      it "assigns the requested demo_user as @demo_user" do
        demo_user = DemoUser.create! valid_attributes
        put :update, {:id => demo_user.to_param, :demo_user => valid_attributes}, valid_session
        assigns(:demo_user).should eq(demo_user)
      end

      it "redirects to the demo_user" do
        demo_user = DemoUser.create! valid_attributes
        put :update, {:id => demo_user.to_param, :demo_user => valid_attributes}, valid_session
        response.should redirect_to(demo_user)
      end
    end

    describe "with invalid params" do
      it "assigns the demo_user as @demo_user" do
        demo_user = DemoUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DemoUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => demo_user.to_param, :demo_user => {  }}, valid_session
        assigns(:demo_user).should eq(demo_user)
      end

      it "re-renders the 'edit' template" do
        demo_user = DemoUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DemoUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => demo_user.to_param, :demo_user => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested demo_user" do
      demo_user = DemoUser.create! valid_attributes
      expect {
        delete :destroy, {:id => demo_user.to_param}, valid_session
      }.to change(DemoUser, :count).by(-1)
    end

    it "redirects to the demo_users list" do
      demo_user = DemoUser.create! valid_attributes
      delete :destroy, {:id => demo_user.to_param}, valid_session
      response.should redirect_to(demo_users_url)
    end
  end

end
