require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SprintActivitiesController do

  # This should return the minimal set of attributes required to create a valid
  # SprintActivity. As you add validations to SprintActivity, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "content" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SprintActivitiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sprint_activities as @sprint_activities" do
      sprint_activity = SprintActivity.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sprint_activities).should eq([sprint_activity])
    end
  end

  describe "GET show" do
    it "assigns the requested sprint_activity as @sprint_activity" do
      sprint_activity = SprintActivity.create! valid_attributes
      get :show, {:id => sprint_activity.to_param}, valid_session
      assigns(:sprint_activity).should eq(sprint_activity)
    end
  end

  describe "GET new" do
    it "assigns a new sprint_activity as @sprint_activity" do
      get :new, {}, valid_session
      assigns(:sprint_activity).should be_a_new(SprintActivity)
    end
  end

  describe "GET edit" do
    it "assigns the requested sprint_activity as @sprint_activity" do
      sprint_activity = SprintActivity.create! valid_attributes
      get :edit, {:id => sprint_activity.to_param}, valid_session
      assigns(:sprint_activity).should eq(sprint_activity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SprintActivity" do
        expect {
          post :create, {:sprint_activity => valid_attributes}, valid_session
        }.to change(SprintActivity, :count).by(1)
      end

      it "assigns a newly created sprint_activity as @sprint_activity" do
        post :create, {:sprint_activity => valid_attributes}, valid_session
        assigns(:sprint_activity).should be_a(SprintActivity)
        assigns(:sprint_activity).should be_persisted
      end

      it "redirects to the created sprint_activity" do
        post :create, {:sprint_activity => valid_attributes}, valid_session
        response.should redirect_to(SprintActivity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sprint_activity as @sprint_activity" do
        # Trigger the behavior that occurs when invalid params are submitted
        SprintActivity.any_instance.stub(:save).and_return(false)
        post :create, {:sprint_activity => { "content" => "invalid value" }}, valid_session
        assigns(:sprint_activity).should be_a_new(SprintActivity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SprintActivity.any_instance.stub(:save).and_return(false)
        post :create, {:sprint_activity => { "content" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sprint_activity" do
        sprint_activity = SprintActivity.create! valid_attributes
        # Assuming there are no other sprint_activities in the database, this
        # specifies that the SprintActivity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SprintActivity.any_instance.should_receive(:update).with({ "content" => "MyString" })
        put :update, {:id => sprint_activity.to_param, :sprint_activity => { "content" => "MyString" }}, valid_session
      end

      it "assigns the requested sprint_activity as @sprint_activity" do
        sprint_activity = SprintActivity.create! valid_attributes
        put :update, {:id => sprint_activity.to_param, :sprint_activity => valid_attributes}, valid_session
        assigns(:sprint_activity).should eq(sprint_activity)
      end

      it "redirects to the sprint_activity" do
        sprint_activity = SprintActivity.create! valid_attributes
        put :update, {:id => sprint_activity.to_param, :sprint_activity => valid_attributes}, valid_session
        response.should redirect_to(sprint_activity)
      end
    end

    describe "with invalid params" do
      it "assigns the sprint_activity as @sprint_activity" do
        sprint_activity = SprintActivity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SprintActivity.any_instance.stub(:save).and_return(false)
        put :update, {:id => sprint_activity.to_param, :sprint_activity => { "content" => "invalid value" }}, valid_session
        assigns(:sprint_activity).should eq(sprint_activity)
      end

      it "re-renders the 'edit' template" do
        sprint_activity = SprintActivity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SprintActivity.any_instance.stub(:save).and_return(false)
        put :update, {:id => sprint_activity.to_param, :sprint_activity => { "content" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sprint_activity" do
      sprint_activity = SprintActivity.create! valid_attributes
      expect {
        delete :destroy, {:id => sprint_activity.to_param}, valid_session
      }.to change(SprintActivity, :count).by(-1)
    end

    it "redirects to the sprint_activities list" do
      sprint_activity = SprintActivity.create! valid_attributes
      delete :destroy, {:id => sprint_activity.to_param}, valid_session
      response.should redirect_to(sprint_activities_url)
    end
  end

end
