require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SprintBoardColumnsController do

  # This should return the minimal set of attributes required to create a valid
  # SprintBoardColumn. As you add validations to SprintBoardColumn, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SprintBoardColumnsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sprint_board_columns as @sprint_board_columns" do
      sprint_board_column = SprintBoardColumn.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sprint_board_columns).should eq([sprint_board_column])
    end
  end

  describe "GET show" do
    it "assigns the requested sprint_board_column as @sprint_board_column" do
      sprint_board_column = SprintBoardColumn.create! valid_attributes
      get :show, {:id => sprint_board_column.to_param}, valid_session
      assigns(:sprint_board_column).should eq(sprint_board_column)
    end
  end

  describe "GET new" do
    it "assigns a new sprint_board_column as @sprint_board_column" do
      get :new, {}, valid_session
      assigns(:sprint_board_column).should be_a_new(SprintBoardColumn)
    end
  end

  describe "GET edit" do
    it "assigns the requested sprint_board_column as @sprint_board_column" do
      sprint_board_column = SprintBoardColumn.create! valid_attributes
      get :edit, {:id => sprint_board_column.to_param}, valid_session
      assigns(:sprint_board_column).should eq(sprint_board_column)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SprintBoardColumn" do
        expect {
          post :create, {:sprint_board_column => valid_attributes}, valid_session
        }.to change(SprintBoardColumn, :count).by(1)
      end

      it "assigns a newly created sprint_board_column as @sprint_board_column" do
        post :create, {:sprint_board_column => valid_attributes}, valid_session
        assigns(:sprint_board_column).should be_a(SprintBoardColumn)
        assigns(:sprint_board_column).should be_persisted
      end

      it "redirects to the created sprint_board_column" do
        post :create, {:sprint_board_column => valid_attributes}, valid_session
        response.should redirect_to(SprintBoardColumn.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sprint_board_column as @sprint_board_column" do
        # Trigger the behavior that occurs when invalid params are submitted
        SprintBoardColumn.any_instance.stub(:save).and_return(false)
        post :create, {:sprint_board_column => { "name" => "invalid value" }}, valid_session
        assigns(:sprint_board_column).should be_a_new(SprintBoardColumn)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SprintBoardColumn.any_instance.stub(:save).and_return(false)
        post :create, {:sprint_board_column => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sprint_board_column" do
        sprint_board_column = SprintBoardColumn.create! valid_attributes
        # Assuming there are no other sprint_board_columns in the database, this
        # specifies that the SprintBoardColumn created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SprintBoardColumn.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => sprint_board_column.to_param, :sprint_board_column => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested sprint_board_column as @sprint_board_column" do
        sprint_board_column = SprintBoardColumn.create! valid_attributes
        put :update, {:id => sprint_board_column.to_param, :sprint_board_column => valid_attributes}, valid_session
        assigns(:sprint_board_column).should eq(sprint_board_column)
      end

      it "redirects to the sprint_board_column" do
        sprint_board_column = SprintBoardColumn.create! valid_attributes
        put :update, {:id => sprint_board_column.to_param, :sprint_board_column => valid_attributes}, valid_session
        response.should redirect_to(sprint_board_column)
      end
    end

    describe "with invalid params" do
      it "assigns the sprint_board_column as @sprint_board_column" do
        sprint_board_column = SprintBoardColumn.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SprintBoardColumn.any_instance.stub(:save).and_return(false)
        put :update, {:id => sprint_board_column.to_param, :sprint_board_column => { "name" => "invalid value" }}, valid_session
        assigns(:sprint_board_column).should eq(sprint_board_column)
      end

      it "re-renders the 'edit' template" do
        sprint_board_column = SprintBoardColumn.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SprintBoardColumn.any_instance.stub(:save).and_return(false)
        put :update, {:id => sprint_board_column.to_param, :sprint_board_column => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sprint_board_column" do
      sprint_board_column = SprintBoardColumn.create! valid_attributes
      expect {
        delete :destroy, {:id => sprint_board_column.to_param}, valid_session
      }.to change(SprintBoardColumn, :count).by(-1)
    end

    it "redirects to the sprint_board_columns list" do
      sprint_board_column = SprintBoardColumn.create! valid_attributes
      delete :destroy, {:id => sprint_board_column.to_param}, valid_session
      response.should redirect_to(sprint_board_columns_url)
    end
  end

end
