require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TaskPositionsController do

  # This should return the minimal set of attributes required to create a valid
  # TaskPosition. As you add validations to TaskPosition, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "task_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TaskPositionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all task_positions as @task_positions" do
      task_position = TaskPosition.create! valid_attributes
      get :index, {}, valid_session
      assigns(:task_positions).should eq([task_position])
    end
  end

  describe "GET show" do
    it "assigns the requested task_position as @task_position" do
      task_position = TaskPosition.create! valid_attributes
      get :show, {:id => task_position.to_param}, valid_session
      assigns(:task_position).should eq(task_position)
    end
  end

  describe "GET new" do
    it "assigns a new task_position as @task_position" do
      get :new, {}, valid_session
      assigns(:task_position).should be_a_new(TaskPosition)
    end
  end

  describe "GET edit" do
    it "assigns the requested task_position as @task_position" do
      task_position = TaskPosition.create! valid_attributes
      get :edit, {:id => task_position.to_param}, valid_session
      assigns(:task_position).should eq(task_position)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TaskPosition" do
        expect {
          post :create, {:task_position => valid_attributes}, valid_session
        }.to change(TaskPosition, :count).by(1)
      end

      it "assigns a newly created task_position as @task_position" do
        post :create, {:task_position => valid_attributes}, valid_session
        assigns(:task_position).should be_a(TaskPosition)
        assigns(:task_position).should be_persisted
      end

      it "redirects to the created task_position" do
        post :create, {:task_position => valid_attributes}, valid_session
        response.should redirect_to(TaskPosition.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved task_position as @task_position" do
        # Trigger the behavior that occurs when invalid params are submitted
        TaskPosition.any_instance.stub(:save).and_return(false)
        post :create, {:task_position => { "task_id" => "invalid value" }}, valid_session
        assigns(:task_position).should be_a_new(TaskPosition)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TaskPosition.any_instance.stub(:save).and_return(false)
        post :create, {:task_position => { "task_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested task_position" do
        task_position = TaskPosition.create! valid_attributes
        # Assuming there are no other task_positions in the database, this
        # specifies that the TaskPosition created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TaskPosition.any_instance.should_receive(:update).with({ "task_id" => "1" })
        put :update, {:id => task_position.to_param, :task_position => { "task_id" => "1" }}, valid_session
      end

      it "assigns the requested task_position as @task_position" do
        task_position = TaskPosition.create! valid_attributes
        put :update, {:id => task_position.to_param, :task_position => valid_attributes}, valid_session
        assigns(:task_position).should eq(task_position)
      end

      it "redirects to the task_position" do
        task_position = TaskPosition.create! valid_attributes
        put :update, {:id => task_position.to_param, :task_position => valid_attributes}, valid_session
        response.should redirect_to(task_position)
      end
    end

    describe "with invalid params" do
      it "assigns the task_position as @task_position" do
        task_position = TaskPosition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TaskPosition.any_instance.stub(:save).and_return(false)
        put :update, {:id => task_position.to_param, :task_position => { "task_id" => "invalid value" }}, valid_session
        assigns(:task_position).should eq(task_position)
      end

      it "re-renders the 'edit' template" do
        task_position = TaskPosition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TaskPosition.any_instance.stub(:save).and_return(false)
        put :update, {:id => task_position.to_param, :task_position => { "task_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested task_position" do
      task_position = TaskPosition.create! valid_attributes
      expect {
        delete :destroy, {:id => task_position.to_param}, valid_session
      }.to change(TaskPosition, :count).by(-1)
    end

    it "redirects to the task_positions list" do
      task_position = TaskPosition.create! valid_attributes
      delete :destroy, {:id => task_position.to_param}, valid_session
      response.should redirect_to(task_positions_url)
    end
  end

end
